# all:
# 	g++ -c *.cpp -o a.o
# 	g++ a.o -o a.exe -lfreeglut -lopengl32 -lglu32

all:
	g++ -lmsmpi -I'/c/Program Files (x86)/Microsoft SDKs/MPI/Include/' *.cpp -lfreeglut -lopengl32 -lglu32 -o a
	# mpiexec a.o -L'/c/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64' -o a.exe -lfreeglut -lopengl32 -lglu32 
